name: CI Pipeline

# Déclencheurs de la pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: npm test
